### ISSUE TITLE
Tom should use XDG directories on Unix (e.g. `~/.config/tom` instead of `~/.tom`)

### ISSUE THREAD

**Issue by klausman** [mlange-42/tom#29]
As per the subject. 

There are Go libraries that somewhat automate this, e.g. github.com/adrg/xdg (this is not an endorsement of that library, it's just the first I found).

**Comment by mlange-42** [comment]
Thanks @klausman for reporting! I am not that familiar with path conventions on Linux. Will check/fix this soon.
