### ISSUE TITLE
Location select screen should use terminal width

### ISSUE THREAD

**Issue by klausman** [mlange-42/tom#30]
E.g. using `tom 'Zürich (Kreis 3'` will yield:

```
Zürich (Kreis 3)         │Zurich│Switzerland│ 47.36°N    8.50°E│46k
Zürich (Kreis 3) / Sihlfe│Zurich│Switzerland│ 47.37°N    8.51°E│20k
Zürich (Kreis 3) / Alt-Wi│      │Switzerland│ 47.36°N    8.51°E│14k
Zürich (Kreis 3) / Gratwe│Zurich│Switzerland│ 47.35°N    8.49°E│3
Zürich (Kreis 3) / Friese│Zurich│Switzerland│ 47.36°N    8.50°E│9k
Zürich (Kreis 3) / Uto-St│Zurich│Switzerland│ 47.35°N    8.50°E│19
Zürich (Kreis 3) / Oberer│Zurich│Switzerland│ 47.35°N    8.50°E│37
Zürich (Kreis 3) / Friese│Zurich│Switzerland│ 47.36°N    8.50°E│133
```

even if the terminal would a much wider width (and thus display longer location names). Note that there are two entries starting with `Zürich (Kreis 3) / Friese`, which makes it unclear which is which, unless you happen to know what 9k vs. 133 means (I don't). That is a secondary issue: not table headers.

**Comment by mlange-42** [comment]
Thanks @klausman for reporting! This screen definitely needs some more work, and I will incorporate your suggestions when going about it.
